### ISSUE TITLE
Confused about durations

### ISSUE THREAD

**Issue by Kagee** [vfaergestad/mattermost-logger#5]
Looking at https://github.com/vfaergestad/mattermost-logger/blob/9d42f0f1b6bfc114d4a635f43dcb5b006101441f/filewriter/filewriter.go#L52 and the related code - why are these hardcoded durations required, why not use the parsed value raw? 

Also, if i am not misunderstanding, the core time.ParseDuration only supports up to hours (h), not days/weeks/months? 🤔

**Comment by Kagee** [comment]
(this is not a blocker for me testing/using the code, i am just confused 😅)

**Comment by vfaergestad** [comment]
> why are these hardcoded durations required, why not use the parsed value raw?

My reasoning for these happened while trying to make the program rotate the files on a "round" number, like 00, 05, 10, 15 for `5m` and 12:00, 13:00 and so on for `1h`. Using the raw input would not fit into this. I considered defaulting to the raw number of it did not match any of the specified values, but decided against it. An "optimal" solution in my eyes would be to just use the raw input AND make it use some sort of "rounded" timestamps, but I could not wrap my head around it at that time. I guess a middle-way would just not caring about the roundness if a non-supported value is used.

> the core time.ParseDuration only supports up to hours (h), not days/weeks/months? 

Good catch, you are absolutely right. Must be me being confused. Using numbers as 168h (1 week) and 720h (1 month) does work though. Going to create a patch for that.

**Comment by vfaergestad** [comment]
Fixed documentation-related issues with 1d, 1w and so on in #6.

**Comment by Kagee** [comment]
Makes enough sense.
